name: Déploiement Angular sur Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Connexion à Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build et push de l'image Docker
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest

    - name: Déploiement sur la VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
        script: |
          echo "Connexion à la VM réussie. Déploiement Docker en cours..."
          docker stop mon-projet-angular || true
          docker rm mon-projet-angular || true
          docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest || true
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest
          docker run -d --name mon-projet-angular -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest
          echo "Déploiement Docker terminé." 