name: Déploiement Angular sur EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v3

      - name: 🔐 Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠️ Build et Push de l'image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest

      - name: 🚀 Déploiement sur la VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            echo "Connexion à la VM réussie. Déploiement Docker en cours..."

            # Supprimer tout conteneur utilisant le port 9090
            EXISTING_CONTAINER=$(docker ps --filter "publish=9090" --format "{{.ID}}")
            if [ ! -z "$EXISTING_CONTAINER" ]; then
              echo "Un conteneur utilise déjà le port 9090. Suppression..."
              docker rm -f $EXISTING_CONTAINER
            fi

            # Supprimer le conteneur précédent s’il existe
            docker rm -f mon-projet-angular || true

            # Supprimer l'image locale (facultatif mais propre)
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest || true

            # Pull et exécution de l'image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest
            docker run -d -p 9090:80 --name mon-projet-angular ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet-angular:latest

            echo "✅ Déploiement Docker terminé avec succès !"
